name: Build, Test and Deploy React Application
on:
  push:
      branches: [master]
  pull_request:  
      branches: [master]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm ci, build and test
      run: |
        npm ci
        npm run build --if-present
        npm test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build

    - name: build and publish package on NPM
      run: |
        git config --global user.email "nadjide.omar.5@gmail.com"
        git config --global user.name "Nadjide"
        npm run build-npm
        npm version patch
        npm publish
        git add .
        git commit -m "update version"
        git push

      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    needs: build_test

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
